// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"time"
)

type Player struct {
	ID      int32  `json:"id"`
	SteamID string `json:"steam_id"`
	UserID  int32  `json:"user_id"`
}

type User struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}
